# Using Pandas

In [72]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 200)
## to make it possible to display multiple output inside one cell 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

<b>load the data from the vehicles.csv file into pandas data frame

In [73]:
# read_csv aplied to loat the dataset
vehicles = pd.read_csv("data/vehicles.csv")
vehicles

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

First exploration of the dataset:

- How many observations does it have?
- Look at all the columns: do you understand what they mean?
- Look at the raw data: do you see anything weird?
- Look at the data types: are they the expected ones for the information the column contains?

In [74]:
# there are 35.952 entries, datatypes: float(4), integer(5), object(6). I see the data types correct. There are makes which are repeated. 
vehicles.info()
print(vehicles["Make"].value_counts())
print(vehicles.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35952 entries, 0 to 35951
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Make                     35952 non-null  object
 1   Model                    35952 non-null  object
 2   Year                     35952 non-null  int64
 3   Engine Displacement      35952 non-null  float64
 4   Cylinders                35952 non-null  float64
 5   Transmission             35952 non-null  object
 6   Drivetrain               35952 non-null  object
 7   Vehicle Class            35952 non-null  object
 8   Fuel Type                35952 non-null  object
 9   Fuel Barrels/Year        35952 non-null  float64
 10  City MPG                 35952 non-null  int64
 11  Highway MPG              35952 non-null  int64
 12  Combined MPG             35952 non-null  int64
 13  CO2 Emission Grams/Mile  35952 non-null  float64
 14  Fuel Cost/Year           35952 non-null  int64
dtypes: float64(4), int64(5), object(6)
memory usage: 4.1+ MB
Chevrolet                             3643
Ford                                  2946
Dodge                                 2360
GMC                                   2347
Toyota                                1836
BMW                                   1677
Mercedes-Benz                         1284
Nissan                                1253
Volkswagen                            1047
Mitsubishi                             950
Mazda                                  915
Audi                                   890
Porsche                                862
Honda                                  836
Jeep                                   829
Pontiac                                784
Subaru                                 781
Volvo                                  717
Hyundai                                662
Chrysler                               641
Buick                                  537
Mercury                                532
Suzuki                                 512
Cadillac                               508
Kia                                    493
Plymouth                               456
Saab                                   410
Isuzu                                  409
Lexus                                  397
Oldsmobile                             376
Infiniti                               345
Jaguar                                 343
MINI                                   320
Acura                                  302
Saturn                                 278
Lincoln                                273
Ferrari                                208
Rolls-Royce                            160
Eagle                                  156
Geo                                    144
Land Rover                             142
Aston Martin                           133
Bentley                                116
Maserati                               111
Lamborghini                            104
Scion                                   83
Peugeot                                 74
Daewoo                                  67
Ram                                     57
Roush Performance                       53
Lotus                                   53
Fiat                                    43
Alfa Romeo                              41
J.K. Motors                             36
Renault                                 33
Wallace Environmental                   32
Maybach                                 31
American Motors Corporation             22
smart                                   20
Hummer                                  19
Daihatsu                                17
CX Automotive                           16
Merkur                                  14
Federal Coach                           14
Import Trade Services                   13
McLaren Automotive                      13
Spyker                                  13
Sterling                                12
Bugatti                                  8
Yugo                                     8
Genesis                                  7
Tecstar, LP                              6
Mcevoy Motors                            6
Saleen                                   5
VPG                                      5
Bertone                                  5
Panther Car Company Limited              4
Saleen Performance                       4
AM General                               4
TVR Engineering Ltd                      4
Grumman Olson                            4
Texas Coach Company                      4
Vector                                   4
Autokraft Limited                        4
Morgan                                   3
Evans Automobiles                        3
Dacia                                    3
Dabryan Coach Builders Inc               3
Consulier Industries Inc                 3
BMW Alpina                               3
Bitter Gmbh and Co. Kg                   3
SRT                                      2
Ruf Automobile Gmbh                      2
CCC Engineering                          2
Red Shift Ltd.                           2
Bill Dovell Motor Car Company            2
Quantum Technologies                     2
Pagani                                   2
PAS, Inc                                 2
Laforza Automobile Inc                   2
Mobility Ventures LLC                    2
Pininfarina                              2
PAS Inc - GMC                            2
Import Foreign Auto Sales Inc            1
London Taxi                              1
London Coach Co Inc                      1
Qvale                                    1
Grumman Allied Industries                1
Vixen Motor Company                      1
Volga Associated Automobile              1
ASC Incorporated                         1
Isis Imports Ltd                         1
Aurora Cars Ltd                          1
JBA Motorcars, Inc.                      1
Mahindra                                 1
Superior Coaches Div E.p. Dutton         1
Goldacre                                 1
General Motors                           1
Fisker                                   1
Shelby                                   1
Panos                                    1
Panoz Auto-Development                   1
Excalibur Autos                          1
S and S Coach Company  E.p. Dutton       1
Environmental Rsch and Devp Corp         1
E. P. Dutton, Inc.                       1
Lambda Control Systems                   1
Name: Make, dtype: int64
               Make                Model  Year  Engine Displacement  \
0        AM General    DJ Po Vehicle 2WD  1984                  2.5
1        AM General     FJ8c Post Office  1984                  4.2
2        AM General  Post Office DJ5 2WD  1985                  2.5
3        AM General  Post Office DJ8 2WD  1985                  4.2
4  ASC Incorporated                  GNX  1987                  3.8

   Cylinders     Transmission        Drivetrain                Vehicle Class  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars

  Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0   Regular          19.388824        18           17            17
1   Regular          25.354615        13           13            13
2   Regular          20.600625        16           17            16
3   Regular          25.354615        13           13            13
4   Premium          20.600625        14           21            16

   CO2 Emission Grams/Mile  Fuel Cost/Year
0               522.764706            1950
1               683.615385            2550
2               555.437500            2100
3               683.615385            2550
4               555.437500            2550

### Cleaning and wrangling data

- Some car brand names refer to the same brand. Replace all brand names that contain the word "Dutton" for simply "Dutton". If you find similar examples, clean their names too. Use `loc` with boolean indexing.

- Convert CO2 Emissions from Grams/Mile to Grams/Km

- Create a binary column that solely indicates if the transmission of a car is automatic or manual. Use `pandas.Series.str.startswith` and .

- convert MPG columns to km_per_liter

# Some car brand names refer to the same brand. Replace all brand names that contain the word "Dutton" for simply "Dutton".

In [75]:
vehicles.loc[vehicles["Make"].str.contains('Dutton') == True, "Make"] = 'Dutton'
vehicles.loc[vehicles["Make"].str.contains('BMW') == True, "Make"] = "BMW"
vehicles.loc[vehicles["Make"].str.contains('Saleen') == True, "Make"] = "Saleen"
vehicles.loc[vehicles["Make"].str.contains('PAS Inc - GMC') == True, "Make"] = "PAS, Inc "
vehicles.loc[vehicles["Make"].str.contains('Panos') == True, "Make"] = "Panoz Auto-Development"

print(vehicles["Make"].value_counts())

Chevrolet                           3643
Ford                                2946
Dodge                               2360
GMC                                 2347
Toyota                              1836
BMW                                 1680
Mercedes-Benz                       1284
Nissan                              1253
Volkswagen                          1047
Mitsubishi                           950
Mazda                                915
Audi                                 890
Porsche                              862
Honda                                836
Jeep                                 829
Pontiac                              784
Subaru                               781
Volvo                                717
Hyundai                              662
Chrysler                             641
Buick                                537
Mercury                              532
Suzuki                               512
Cadillac                             508
Kia                                  493
Plymouth                             456
Saab                                 410
Isuzu                                409
Lexus                                397
Oldsmobile                           376
Infiniti                             345
Jaguar                               343
MINI                                 320
Acura                                302
Saturn                               278
Lincoln                              273
Ferrari                              208
Rolls-Royce                          160
Eagle                                156
Geo                                  144
Land Rover                           142
Aston Martin                         133
Bentley                              116
Maserati                             111
Lamborghini                          104
Scion                                 83
Peugeot                               74
Daewoo                                67
Ram                                   57
Roush Performance                     53
Lotus                                 53
Fiat                                  43
Alfa Romeo                            41
J.K. Motors                           36
Renault                               33
Wallace Environmental                 32
Maybach                               31
American Motors Corporation           22
smart                                 20
Hummer                                19
Daihatsu                              17
CX Automotive                         16
Merkur                                14
Federal Coach                         14
Import Trade Services                 13
McLaren Automotive                    13
Spyker                                13
Sterling                              12
Saleen                                 9
Bugatti                                8
Yugo                                   8
Genesis                                7
Mcevoy Motors                          6
Tecstar, LP                            6
Bertone                                5
VPG                                    5
TVR Engineering Ltd                    4
Texas Coach Company                    4
Panther Car Company Limited            4
AM General                             4
Autokraft Limited                      4
Grumman Olson                          4
Vector                                 4
Morgan                                 3
Evans Automobiles                      3
Consulier Industries Inc               3
Dabryan Coach Builders Inc             3
Dacia                                  3
Bitter Gmbh and Co. Kg                 3
Dutton                                 3
Laforza Automobile Inc                 2
Quantum Technologies                   2
Pininfarina                            2
PAS, Inc                               2
Red Shift Ltd.                         2
Bill Dovell Motor Car Company          2
Panoz Auto-Development                 2
Ruf Automobile Gmbh                    2
SRT                                    2
Pagani                                 2
Mobility Ventures LLC                  2
CCC Engineering                        2
PAS, Inc                               2
Vixen Motor Company                    1
Volga Associated Automobile            1
Aurora Cars Ltd                        1
Lambda Control Systems                 1
Shelby                                 1
Qvale                                  1
Excalibur Autos                        1
Fisker                                 1
General Motors                         1
Goldacre                               1
Grumman Allied Industries              1
Import Foreign Auto Sales Inc          1
Mahindra                               1
Isis Imports Ltd                       1
London Taxi                            1
London Coach Co Inc                    1
JBA Motorcars, Inc.                    1
ASC Incorporated                       1
Environmental Rsch and Devp Corp       1
Name: Make, dtype: int64

# Convert CO2 Emissions from Grams/Mile to Grams/Km

In [76]:
print(vehicles.loc[:,"CO2 Emission Grams/Mile"])
vehicles.loc[:,"CO2 Emission Grams/Mile"] = vehicles.loc[:,"CO2 Emission Grams/Mile"] / 1.60934
vehicles.rename(columns = {'CO2 Emission Grams/Mile':'CO2 Emission Grams/Km'}, inplace = True)
print(vehicles['CO2 Emission Grams/Km'].head())

0        522.764706
1        683.615385
2        555.437500
3        683.615385
4        555.437500
            ...
35947    244.000000
35948    243.000000
35949    244.000000
35950    246.000000
35951    255.000000
Name: CO2 Emission Grams/Mile, Length: 35952, dtype: float64
0    324.831736
1    424.779962
2    345.133719
3    424.779962
4    345.133719
Name: CO2 Emission Grams/Km, dtype: float64

# Convert MPG columns to km_per_liter

In [77]:
print(vehicles.loc[:,"City MPG"])
vehicles.loc[:,"City MPG"] = vehicles.loc[:,"City MPG"] * (1.60934 / 3.78541)

print(vehicles.loc[:,"Highway MPG"])
vehicles.loc[:,"Highway MPG"] = vehicles.loc[:,"Highway MPG"] * (1.60934 / 3.78541)

print(vehicles.loc[:,"Combined MPG"])
vehicles.loc[:,"Combined MPG"] = vehicles.loc[:,"Combined MPG"] * (1.60934 / 3.78541)

0        18
1        13
2        16
3        13
4        14
         ..
35947    34
35948    34
35949    34
35950    34
35951    32
Name: City MPG, Length: 35952, dtype: int64
0        17
1        13
2        17
3        13
4        21
         ..
35947    38
35948    38
35949    38
35950    39
35951    39
Name: Highway MPG, Length: 35952, dtype: int64
0        17
1        13
2        16
3        13
4        16
         ..
35947    36
35948    36
35949    36
35950    36
35951    35
Name: Combined MPG, Length: 35952, dtype: int64

# Create a binary column that solely indicates if the transmission of a car is automatic or manual.

In [88]:
transmission_binary = []
for item in list(vehicles["Transmission"]):
    if item.startswith("A") == True:
        transmission_binary.append("Automatic")
    else:
        transmission_binary.append("Manual")
vehicles["Binary Transmission"] = transmission_binary
print(vehicles.head())

               Make                Model  Year  Engine Displacement  \
0        AM General    DJ Po Vehicle 2WD  1984                  2.5
1        AM General     FJ8c Post Office  1984                  4.2
2        AM General  Post Office DJ5 2WD  1985                  2.5
3        AM General  Post Office DJ8 2WD  1985                  4.2
4  ASC Incorporated                  GNX  1987                  3.8

   Cylinders     Transmission        Drivetrain                Vehicle Class  \
0        4.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD
1        6.0  Automatic 3-spd     2-Wheel Drive  Special Purpose Vehicle 2WD
2        4.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD
3        6.0  Automatic 3-spd  Rear-Wheel Drive  Special Purpose Vehicle 2WD
4        6.0  Automatic 4-spd  Rear-Wheel Drive                 Midsize Cars

  Fuel Type  Fuel Barrels/Year  City MPG  Highway MPG  Combined MPG  \
0   Regular          19.388824  7.652571     7.227428      7.227428
1   Regular          25.354615  5.526857     5.526857      5.526857
2   Regular          20.600625  6.802286     7.227428      6.802286
3   Regular          25.354615  5.526857     5.526857      5.526857
4   Premium          20.600625  5.952000     8.928000      6.802286

   CO2 Emission Grams/Km  Fuel Cost/Year Binary Transmission
0             324.831736            1950           Automatic
1             424.779962            2550           Automatic
2             345.133719            2100           Automatic
3             424.779962            2550           Automatic
4             345.133719            2550           Automatic

Converting Grams/Mile to Grams/Km

1 Mile = 1.60934 Km

Grams/Mile * Mile/Km -> Grams/Mile * 1 Mile/1.60934Km

$$ \frac{Grams}{Mile} * \frac{Mile}{Km} $$

$$ \frac{Grams}{Mile} * \frac{1 Mile}{1.60934Km}  $$

convert MPG columns to km_per_liter

MPG = Miles/Gallon -> Km/Liter

1 Mile = 1.60934 Km

1 Gallon = 3.78541 Liters

$$ \frac{Miles}{Gallon} -> \frac{Miles}{Gallon} * \frac{Km}{Miles} * \frac{Gallon}{Liters}$$

$$ \frac{Miles}{Gallon} -> \frac{Miles}{Gallon} * \frac{1.60934Km}{ 1Miles} * \frac{1 Gallon}{3.78541 Liters}$$

* ( 1.60934 / 3.78541 )

### Gathering insights:

- How many car makers are there? How many models? Which car maker has the most cars in the dataset?

- When were these cars made? How big is the engine of these cars?

- What's the frequency of different transmissions, drivetrains and fuel types?

- What's the car that consumes the least/most fuel?

# How many car makers are there? How many models? Which car maker has the most cars in the dataset?

In [67]:
#number of cars. Using tolist to convert it to a list
len(vehicles['Make'].unique().tolist())

122

In [59]:
#brand with most cars. Chevrolet would be the one with the higher number of cars
vehicles['Make'].value_counts()

Chevrolet                           3643
Ford                                2946
Dodge                               2360
GMC                                 2347
Toyota                              1836
BMW                                 1680
Mercedes-Benz                       1284
Nissan                              1253
Volkswagen                          1047
Mitsubishi                           950
Mazda                                915
Audi                                 890
Porsche                              862
Honda                                836
Jeep                                 829
Pontiac                              784
Subaru                               781
Volvo                                717
Hyundai                              662
Chrysler                             641
Buick                                537
Mercury                              532
Suzuki                               512
Cadillac                             508
Kia                                  493
Plymouth                             456
Saab                                 410
Isuzu                                409
Lexus                                397
Oldsmobile                           376
Infiniti                             345
Jaguar                               343
MINI                                 320
Acura                                302
Saturn                               278
Lincoln                              273
Ferrari                              208
Rolls-Royce                          160
Eagle                                156
Geo                                  144
Land Rover                           142
Aston Martin                         133
Bentley                              116
Maserati                             111
Lamborghini                          104
Scion                                 83
Peugeot                               74
Daewoo                                67
Ram                                   57
Roush Performance                     53
Lotus                                 53
Fiat                                  43
Alfa Romeo                            41
J.K. Motors                           36
Renault                               33
Wallace Environmental                 32
Maybach                               31
American Motors Corporation           22
smart                                 20
Hummer                                19
Daihatsu                              17
CX Automotive                         16
Merkur                                14
Federal Coach                         14
Import Trade Services                 13
McLaren Automotive                    13
Spyker                                13
Sterling                              12
Saleen                                 9
Bugatti                                8
Yugo                                   8
Genesis                                7
Mcevoy Motors                          6
Tecstar, LP                            6
Bertone                                5
VPG                                    5
TVR Engineering Ltd                    4
Texas Coach Company                    4
Panther Car Company Limited            4
AM General                             4
Autokraft Limited                      4
Grumman Olson                          4
Vector                                 4
Morgan                                 3
Evans Automobiles                      3
Consulier Industries Inc               3
Dabryan Coach Builders Inc             3
Dacia                                  3
Bitter Gmbh and Co. Kg                 3
Dutton                                 3
Laforza Automobile Inc                 2
Quantum Technologies                   2
Pininfarina                            2
PAS, Inc                               2
Red Shift Ltd.                         2
Bill Dovell Motor Car Company          2
Panoz Auto-Development                 2
Ruf Automobile Gmbh                    2
SRT                                    2
Pagani                                 2
Mobility Ventures LLC                  2
CCC Engineering                        2
PAS, Inc                               2
Vixen Motor Company                    1
Volga Associated Automobile            1
Aurora Cars Ltd                        1
Lambda Control Systems                 1
Shelby                                 1
Qvale                                  1
Excalibur Autos                        1
Fisker                                 1
General Motors                         1
Goldacre                               1
Grumman Allied Industries              1
Import Foreign Auto Sales Inc          1
Mahindra                               1
Isis Imports Ltd                       1
London Taxi                            1
London Coach Co Inc                    1
JBA Motorcars, Inc.                    1
ASC Incorporated                       1
Environmental Rsch and Devp Corp       1
Name: Make, dtype: int64

In [68]:
#unique models
len(vehicles['Model'].unique().tolist())

3608

# What brand has the worse CO2 Emissions on average?

Hint: use the function `sort_values()`

In [81]:
# The brand with worse CO2 Emissions would be Lanborghini
vehicles.sort_values("CO2 Emission Grams/Km", ascending = False)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Km,Fuel Cost/Year
20897,Lamborghini,Countach,1989,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2.550857,4.251429,2.976000,788.877073,5800
20898,Lamborghini,Countach,1990,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2.550857,4.251429,2.976000,788.877073,5800
20896,Lamborghini,Countach,1988,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2.550857,4.251429,2.976000,788.877073,5800
20895,Lamborghini,Countach,1987,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2.550857,4.251429,2.976000,788.877073,5800
20894,Lamborghini,Countach,1986,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2.550857,4.251429,2.976000,788.877073,5800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7917,Chevrolet,Volt,2017,1.5,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Compact Cars,Regular Gas or Electricity,2.006844,18.281143,17.856000,17.856000,31.690010,800
7916,Chevrolet,Volt,2016,1.5,4.0,Automatic (variable gear ratios),Front-Wheel Drive,Compact Cars,Regular Gas or Electricity,2.006844,18.281143,17.856000,17.856000,31.690010,800
3070,BMW,i3 REX,2015,0.6,2.0,Automatic (A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,17.430857,15.730285,16.580571,24.854909,1050
3069,BMW,i3 REX,2014,0.6,2.0,Auto(A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,17.430857,15.730285,16.580571,24.854909,1050
3071,BMW,i3 REX,2016,0.6,2.0,Automatic (A1),Rear-Wheel Drive,Subcompact Cars,Premium Gas or Electricity,1.563190,17.430857,15.730285,16.580571,22.990791,1050

# Do cars with automatic transmission consume more fuel than cars with manual transmission on average?

In [89]:
vehicles.groupby("Binary Transmission")[["Fuel Cost/Year"]].mean().sort_values("Fuel Cost/Year")

                     Fuel Cost/Year
Binary Transmission
Manual                  1785.765735
Automatic               1943.890490

# When were these cars made? How big is the engine of these cars?

In [96]:
vehicles['Year'].value_counts()

1985    1581
2015    1264
2016    1228
2014    1211
1987    1198
1986    1188
2008    1184
2009    1183
2013    1168
2005    1156
2012    1139
1989    1127
2007    1126
2011    1124
1991    1122
1988    1119
2004    1113
2010    1108
1992    1107
2006    1099
1993    1077
1990    1068
2003    1034
1994     967
2002     961
1995     928
2001     902
2017     857
1999     828
2000     827
1998     791
1996     767
1997     755
1984     645
Name: Year, dtype: int64

# What's the frequency of different transmissions, drivetrains and fuel types?

In [91]:
vehicles['Binary Transmission'].value_counts()

Automatic    24290
Manual       11662
Name: Binary Transmission, dtype: int64

In [93]:
vehicles['Fuel Type'].value_counts()

Regular                        23587
Premium                         9921
Gasoline or E85                 1195
Diesel                           911
Premium or E85                   121
Midgrade                          74
CNG                               60
Premium and Electricity           20
Gasoline or natural gas           20
Premium Gas or Electricity        17
Regular Gas and Electricity       16
Gasoline or propane                8
Regular Gas or Electricity         2
Name: Fuel Type, dtype: int64

# What's the car that consumes the least/most fuel?

In [99]:
vehicles[vehicles['Fuel Barrels/Year'] == vehicles['Fuel Barrels/Year'].max()]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Km,Fuel Cost/Year,Binary Transmission
20894,Lamborghini,Countach,1986,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2.550857,4.251429,2.976,788.877073,5800,Manual
20895,Lamborghini,Countach,1987,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2.550857,4.251429,2.976,788.877073,5800,Manual
20896,Lamborghini,Countach,1988,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2.550857,4.251429,2.976,788.877073,5800,Manual
20897,Lamborghini,Countach,1989,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2.550857,4.251429,2.976,788.877073,5800,Manual
20898,Lamborghini,Countach,1990,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,2.550857,4.251429,2.976,788.877073,5800,Manual

In [101]:
vehicles[vehicles['Fuel Barrels/Year'] == vehicles['Fuel Barrels/Year'].min()]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Km,Fuel Cost/Year,Binary Transmission
17395,Honda,Civic Natural Gas,2012,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.06,11.478857,16.155428,13.179428,142.104437,1000,Automatic
17396,Honda,Civic Natural Gas,2013,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.06,11.478857,16.155428,13.179428,135.459257,1000,Automatic
17397,Honda,Civic Natural Gas,2014,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.06,11.478857,16.155428,13.179428,135.459257,1000,Automatic
17398,Honda,Civic Natural Gas,2015,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.06,11.478857,16.155428,13.179428,135.459257,1000,Automatic